/**
 ******************************************************************************
 * @file    main.c
 * @author  Auto-generated by STM32CubeIDE
 * @version V1.0
 * @brief   Default main function.
 ******************************************************************************
 */

#define STM32F407xx
#include "stm32f4xx.h"
#include <stdbool.h>
#include "LedModule.h"



int main(void) {

	uint8_t savedDisplayData[8] = { 0 };

	CLOCK_init();
	SPI_init();

	//Display Test Register
	spiTransmit(CODE_DISPLAYTEST, 0);

	//Intensity Register Mode
	spiTransmit(CODE_INTENSITY, INTENSITY_LEVEL8);

	//Scan-Limit Register
	spiTransmit(CODE_SCANLIMIT, 7);

	//Decode Mode
	spiTransmit(CODE_DECODEMODE, 0);

	//Shutdown Mode on
	shutdown(true);

	//Shutdown off
	shutdown(false);

	clearDisplay(savedDisplayData);

	//char text[] = "ABCDE";
	//uint8_t sizeoftext = strlen(text);

	//write_a_text_on_screen(text,  sizeoftext);




	spiDisable();

}

